version: '3.8'

services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-truck_monitoring}
      POSTGRES_USER: ${POSTGRES_USER:-truck_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  redis:
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build:
      target: production
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      SERVICE_NAME: ${SERVICE_NAME:-truck-monitoring-backend}
      SERVICE_VERSION: ${SERVICE_VERSION:-1.0.0}
      NODE_ENV: production
      PORT: 3000
    volumes: []
    restart: always

  frontend:
    build:
      target: production
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_ENVIRONMENT: production
      REACT_APP_WEBSOCKET_URL: ${REACT_APP_WEBSOCKET_URL}
    volumes: []
    restart: always

  nginx:
    profiles: []
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    environment:
      - NGINX_HOST=${DOMAIN_NAME:-localhost}
    restart: always

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true